### ISSUE TITLE
[1주차] 1장, 2장

### ISSUE THREAD

**Issue by kty0529** [Meet-Coder-Study/book_designing_for_performance#1]
## 2장

1. DOM 트리가 그려질 때 CSS를 만나면 잠시 멈췄다가 다시 그리는건 처음 알았습니다,
한번에 다 그리고 시작하는줄 알았어요 😅
2. 책 27페이지의 Timeline 이라는 크롬 개발자도구 탭을 보고싶은데 못찾겠네요.
혹시 위치를 아시는분이 계실까요? (타임라인이 사라지고 퍼포먼스가 되었을까요?)

이외 내용들은 책을 더 읽어보면 좋겠네요. 🙂

- https://www.webpagetest.org/

**Comment by ksy90101** [comment]
2. https://stackoverflow.com/questions/46306244/google-devtools-timeline-panel-missing
